import type { SitePreset } from "./types";

export const jeleniaGoraPreset: SitePreset = {
  id: "jelenia-gora",
  label: "Jelenia Góra",
  siteName: "Supernowa",
  companyLegalName: "Supernowa Tomasz Piekarski",
  siteCity: "Jelenia Góra i okolice",
  cityLocative: "w Jeleniej Górze",
  siteDefaultUrl: "https://supernowa-jg.pl",
  email: "supernowatpiekarski@gmail.com",
  phoneDisplay: "533 843 330",
  phoneE164: "+48533843330",
  address: "",
  addressStreet: "",
  addressCity: "Jelenia Góra",
  addressPostal: "",
  serviceArea: "Jelenia Góra i okolice",
  mapsQuery: "Supernowa Tomasz Piekarski Jelenia Góra",
  mapsUrl: "https://maps.app.goo.gl/6L8LBrDv8HoJPTsKA",
  nip: "611-256-26-86",
  regon: "022391957",
  hours: "Pn - Pt: 9:00 - 17:00",
  logoUrl: "/logo.png",
  heroImage: "/gallery/buderus-gb172.webp",
  siteTitle: "Serwis kotłów Jelenia Góra | Supernowa",
  siteKeywords:
    "serwis kotłów Jelenia Góra, serwis pomp ciepła, Buderus serwis, Bosch serwis, Junkers serwis, Termet serwis, Broetje serwis, Kaisai, pierwsze uruchomienie kotła, naprawa kotła gazowego, przegląd kotła Jelenia Góra",
  siteDescription:
    "Serwis gwarancyjny i pogwarancyjny kotłów gazowych oraz pomp ciepła w Jeleniej Górze i okolicach. Naprawy, przeglądy, pierwsze uruchomienia — dojazd do klienta. Zadzwoń: 533 843 330.",
  ogImage: "/gallery/buderus-gb172.webp",
  googleRating: 4.8,
  googleReviewCount: 51,
  googleReviewsUrl: "https://maps.app.goo.gl/6L8LBrDv8HoJPTsKA",
  partners: ["Buderus", "Bosch", "Junkers", "Termet", "Broetje", "Kaisai"],
  gallery: [
    {
      image: "/gallery/buderus-gb172.webp",
      alt: "Przegląd i serwis kotła gazowego Buderus GB172 — Supernowa, Jelenia Góra",
      caption: "Buderus GB172 · przegląd serwisowy",
    },
    {
      image: "/gallery/buderus-kaskada.webp",
      alt: "Serwis kaskady kotłów Buderus — Supernowa, Jelenia Góra",
      caption: "Kaskada · konserwacja instalacji",
    },
    {
      image: "/gallery/buderus-gb172-2.webp",
      alt: "Konserwacja kotła Buderus GB172 — Supernowa, Jelenia Góra",
      caption: "GB172 · serwis urządzenia",
    },
    {
      image: "/gallery/buderus-gb192.webp",
      alt: "Serwis kotła kondensacyjnego Buderus GB192 — Supernowa, Jelenia Góra",
      caption: "Buderus GB192 · przegląd i regulacja",
    },
    {
      image: "/gallery/buderus-pompa-ciepla.webp",
      alt: "Serwis pompy ciepła Buderus Logatherm — Supernowa, Jelenia Góra",
      caption: "Logatherm · serwis pompy ciepła",
    },
  ],
  reviews: [
    {
      name: "M. K.",
      text: "Pan Tomasz Piekarski to fachowiec, którego z pełnym przekonaniem mogę polecić. Dwukrotnie uratował nas, gdy nasz piec uległ awarii — przyjechał szybko i skutecznie usunął usterki. Profesjonalizm i doświadczenie widać na każdym kroku. Zdecydowanie już nie będziemy szukać innego serwisanta.",
      source: "google",
      rating: 5,
      relativeTime: "rok temu",
    },
    {
      name: "R. T.",
      text: "Doskonały fachowiec, znawca tematu. Już w pierwszej chwili wiedział, co mojej maszynie (dwufunkcyjny Buderus) dolega. Błyskawiczna naprawa i pełne zadowolenie. Wysoka kultura osobista — polecam i dziękuję!",
      source: "google",
      rating: 5,
      relativeTime: "2 lata temu",
    },
    {
      name: "A. W.",
      text: "Wyjątkowo rzetelny fachowiec. Słowny i kompetentny. Polecam!",
      source: "google",
      rating: 5,
      relativeTime: "rok temu",
    },
    {
      name: "J. P.",
      text: "Wiedza, doświadczenie, odpowiednie narzędzia i pasja do pracy — to cechuje Pana Tomasza Piekarskiego. Współpraca z firmą Supernowa to czysta przyjemność i wygoda. Polecamy!",
      source: "google",
      rating: 5,
      relativeTime: "2 lata temu",
    },
    {
      name: "M. R.",
      text: "Reakcja błyskawiczna, fachowa, profesjonalna. Od razu usunął awarię. Pan Tomasz sympatyczny i empatyczny — polecam bardzo serwis Supernowa.",
      source: "google",
      rating: 5,
      relativeTime: "rok temu",
    },
  ],
};
